### ISSUE TITLE
Set boundary_augmentation flag in training notebook

### ISSUE THREAD

**Issue by quantumjot** [lowe-lab-ucl/cnn-annotator#10]
In the training notebook, there is:

```python
@augmentation_label_handler
def augment(img):
    boundary_augmentation=True
    if boundary_augmentation:
```

we should set this as a flag at the beginning of the notebook, e.g.:
``` python
BOUNDARY_AUGMENTATION = True

...

@augmentation_label_handler
def augment(img):
    if BOUNDARY_AUGMENTATION:
```

**Comment by KristinaUlicna** [comment]
I edited the image patches which need padding around the edged to contain "_flagged.tif" at the end of their file name, and modifies the TFrecord function to exclude such files. I think it fixes the problem for now.
