### ISSUE TITLE
Testing the protocol

### ISSUE THREAD

**Issue by quantumjot** [lowe-lab-ucl/cnn-annotator#11]
@nthndy (Nathan) has agreed to test your protocol once done - let's see if it all works!

**Comment by nthndy** [comment]
You can all call me Mr Inspector from now on

**Comment by nthndy** [comment]
## Only two issues I noticed that I could not rectify:

1. Confusion matrix seemed to get a little confused. 
2. UMAP creation failed.

For the confusion matrix, it seemed as if the diagonal values were listed incorrectly. I will show my input images (excuse the test data set, I was having a play around with Fucci data). 

![Screenshot from 2021-03-13 18-26-52](https://user-images.githubusercontent.com/16838461/111040214-ccd57980-8429-11eb-9cc1-3cc06aa23083.png)
![Screenshot from 2021-03-13 18-28-07](https://user-images.githubusercontent.com/16838461/111040232-e2e33a00-8429-11eb-955f-ece957384776.png)

As you can see the two different diagonals are mislabelled, there were 18 mitoses examples and only 1 S_G2.

The UMAP creation failure I didn't really know why but seems quite solvable based on the mixed up dimensions of the input array. 

![Screenshot from 2021-03-13 18-31-29](https://user-images.githubusercontent.com/16838461/111040315-59803780-842a-11eb-83d0-03d33d4d0e2d.png)

**Comment by nthndy** [comment]
Will also add some non-code issues to the goog doc as well as general comments

**Comment by nthndy** [comment]
Sorry, forgot that I had an error that appeared when I changed the cell state names to my own input. For some reason it did not allow the first cell state name to be anything but interphase. You can change the rest of the cell state names but it will only proceed if the first is interphase.
![Screenshot from 2021-03-13 18-38-12](https://user-images.githubusercontent.com/16838461/111040549-491c8c80-842b-11eb-92c4-da291911ae2c.png)

**Comment by laureho** [comment]
@chris-soelistyo can you have a look at the confusion matrix's confusion that Nathan reported above?

**Comment by quantumjot** [comment]
This is great - thanks for the feedback @nthndy !
