### ISSUE TITLE
Replace annotation file loader with cellx version

### ISSUE THREAD

**Issue by quantumjot** [lowe-lab-ucl/cnn-annotator#22]
In PR https://github.com/quantumjot/cellx/pull/26 , I've added a generic reader for the annotation zip files.

This means we should replace the code in notebooks C and D (`create_tf_record`) with versions that use this loader:
```python
from cellx.tools.io import read_annotations

images, labels, states = read_annotations("/path/to/annotations")
LABELS = list(states.keys())
```

This means we don't have to hard code anything in the notebooks, should the labels change etc..

Link to the cellx code:
https://github.com/quantumjot/cellx/blob/2eb468f9f3b6ab9e13d0d951bb73975aa51e66df/cellx/tools/io.py#L183-L202

**Comment by laureho** [comment]
We should also include a boolean for padded patches in order to allow excluding edge images from training.

**Comment by quantumjot** [comment]
> We should also include a boolean for padded patches in order to allow excluding edge images from training.

I added this: https://github.com/quantumjot/cellx/pull/27
