### ISSUE TITLE
Organise the repo

### ISSUE THREAD

**Issue by quantumjot** [lowe-lab-ucl/cnn-annotator#3]
We should organise the repo a little more, e.g.:
```
notebooks/
data/
  MDCK_H2B_GFP_movie.tif
  annotation_02-08-2021--10-33-59.zip
  ...
assets/
  cell_cycle_states.png
  ...
```

**Comment by quantumjot** [comment]
@KristinaUlicna - once @chris-soelistyo has merged #5 , could you take a look at cleaning up the rest of the repo?

**Comment by quantumjot** [comment]
Could you also add an image to the README to show either the napari plugin working or an idea of the workflow?

**Comment by KristinaUlicna** [comment]
The `annotation` zipfiles are saved into the same directory as the notebooks by default. Would you like to have this updated & create a new `data` folder to store these in?

**Comment by quantumjot** [comment]
I think it's fine to save out to the same folder as the notebooks. But these example data can be put in the new `data` folder. What do you think?

**Comment by KristinaUlicna** [comment]
The annotation files will now be created in the `../data` folder. All good!
