### ISSUE TITLE
UMAP image patch projection fails due to wrong test images variable

### ISSUE THREAD

**Issue by laureho** [lowe-lab-ucl/cnn-annotator#34]
2. UMAP creation failed. 

![Screenshot from 2021-03-13 18-31-29](https://user-images.githubusercontent.com/16838461/111040315-59803780-842a-11eb-83d0-03d33d4d0e2d.png)

_Originally posted by @nthndy in https://github.com/lowe-lab-ucl/cnn-annotator/issues/11#issuecomment-798752063_

**Comment by quantumjot** [comment]
It seems like there may be an error with concatenation of images here, i.e. 3x concatenate 64x64 --> (64, 192), versus 3x concat 64x64x1 --> (64, 64, 3)

**Comment by laureho** [comment]
yep, I figured out what the issue was, was just waiting for the various changes to the notebooks to be merged first!
