### ISSUE TITLE
UMAP in notebook D doesn't import

### ISSUE THREAD

**Issue by KristinaUlicna** [lowe-lab-ucl/cnn-annotator#42]
In the ntbk-D import cell, the `from umap import UMAP` line cannot execute - return an error 'No module named umap' 

Also, the [umap package](https://pypi.org/project/umap/) is not listed in the `requirements.txt` nor in the `environment.yml` files.

Having a look at the pypi wheel, isn't it the `umap-learn` package that we need to `pip install`?: 
https://pypi.org/project/umap-learn/

**Comment by quantumjot** [comment]
Can we just replace `from umap import UMAP` with `from umap-learn import UMAP` or has the whole package changed?

**Comment by laureho** [comment]
I just need to add a `pip install`, the package is called `umap-learn` but the import statement needs to be `import umap`. It was like that from the beginning.

**Comment by laureho** [comment]
> Also, the [umap package](https://pypi.org/project/umap/) is not listed in the `requirements.txt` nor in the `environment.yml` files.

Didn't add `umap-learn` to the virtual env requirements because these only account for the notebooks designed to be run outside of Colab, i.e. notebooks A & B
