### ISSUE TITLE
Annotator ntbk doesn't work with latest napari version

### ISSUE THREAD

**Issue by KristinaUlicna** [lowe-lab-ucl/cnn-annotator#43]
The annotator doesn’t work with the lastest version of napari (currently: `napari==0.4.8-rc3`). *Temp solution:* by downgrading napari to version 0.4.4 (works!)

**Comment by quantumjot** [comment]
Can you post the error log?

**Comment by KristinaUlicna** [comment]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/opt/anaconda3/envs/cnn-annotator/lib/python3.7/site-packages/napari/_qt/qt_event_loop.py in gui_qt(startup_logo=False, gui_exceptions=False, force=False)
    248         splash.close()
    249     try:
--> 250         yield app
        app = <PyQt5.QtWidgets.QApplication object at 0x7f9968511190>
    251     except Exception:
    252         notification_manager.receive_error(*sys.exc_info())

<ipython-input-8-14b6921a85a8> in <module>
      4     viewer.add_image(data, name='GFP', metadata=metadata)
      5 
----> 6     annotator(viewer)
        global annotator = <function annotator at 0x7f9988892050>
        global viewer = Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 224.5, 299.5), zoom=0.8469115191986644, angles=(0.0, 0.0, 90.0), interactive=True), cursor=Cursor(position=(0.0, 0.0, 0.0), scaled=True, size=1, style='pointing'), dims=Dims(ndim=3, ndisplay=2, last_used=2, range=((0.0, 49.0, 1.0), (0.0, 449.0, 1.0), (0.0, 599.0, 1.0)), current_step=(0, 0, 0), order=(0, 1, 2), axis_labels=('0', '1', '2')), grid=GridCanvas(enabled=False, stride=1, shape=(-1, -1)), layers=[<Image layer 'GFP' at 0x7f99a86745d0>, <Points layer 'Annotation' at 0x7f9979771d50>], scale_bar=ScaleBar(visible=False, colored=False, ticks=True, position='bottom_right'), active_layer=<Points layer 'Annotation' at 0x7f9979771d50>, help='', status='Ready', theme='dark', title='napari', mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x7f9968ac0290>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})
      7 

<ipython-input-7-f32376ba73d6> in annotator(viewer=Viewer(axes=Axes(visible=False, labels=True, col...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}))
     12 
     13     points_layer.mode = 'add'
---> 14     points_layer.face_color = 'State'
        global points_layer.face_color = undefined
     15     points_layer.face_color_cycle = COLOR_CYCLE
     16     points_layer.face_color_mode = 'cycle'

~/opt/anaconda3/envs/cnn-annotator/lib/python3.7/site-packages/napari/layers/points/points.py in face_color(self=<Points layer 'Annotation'>, face_color='State')
    788             n_colors=len(self.data),
    789             properties=self.properties,
--> 790             current_properties=self.current_properties,
        global current_properties = undefined
        self.current_properties = {'State': array(['Interphase'], dtype='<U10')}
    791         )
    792         self.events.face_color()

~/opt/anaconda3/envs/cnn-annotator/lib/python3.7/site-packages/napari/layers/utils/color_manager.py in _set_color(self=ColorManager(current_color=array([1., 1., 1., 1....), colors=array([], shape=(0, 4), dtype=float64)), color='State', n_colors=0, properties={'State': array([], dtype='<U12')}, current_properties={'State': array(['Interphase'], dtype='<U10')})
    221                 self.color_mode = ColorMode.COLORMAP
    222             else:
--> 223                 self.color_mode = ColorMode.CYCLE
        self.color_mode = 'direct'
        global ColorMode.CYCLE = <ColorMode.CYCLE: 'cycle'>
    224         else:
    225             transformed_color = transform_color_with_defaults(

~/opt/anaconda3/envs/cnn-annotator/lib/python3.7/site-packages/napari/utils/events/evented_model.py in __setattr__(self=ColorManager(current_color=array([1., 1., 1., 1....), colors=array([], shape=(0, 4), dtype=float64)), name='color_mode', value=<ColorMode.CYCLE: 'cycle'>)
    146 
    147         # set value using original setter
--> 148         super().__setattr__(name, value)
        global super.__setattr__ = undefined
        name = 'color_mode'
        value = <ColorMode.CYCLE: 'cycle'>
    149 
    150         # if different we emit the event with new value

~/opt/anaconda3/envs/cnn-annotator/lib/python3.7/site-packages/pydantic/main.cpython-37m-darwin.so in pydantic.main.BaseModel.__setattr__()

~/opt/anaconda3/envs/cnn-annotator/lib/python3.7/site-packages/napari/layers/utils/color_manager.py in _validate_colors(cls=<class 'napari.layers.utils.color_manager.ColorManager'>, values={'categorical_colormap': CategoricalColormap(colormap={}, fallback_color=...ycle=<itertools.cycle object at 0x7f99797a7be0>)), 'color_mode': 'cycle', 'color_properties': ColorProperties(name='State', values=array([], d... current_value=array('Interphase', dtype='<U10')), 'colors': array([], shape=(0, 4), dtype=float64), 'continuous_colormap': Colormap(colors=array([[0.26700401, 0.004874  , ...529, 0.99215686, 0.99607843,
       1.        ])), 'contrast_limits': None, 'current_color': array([1., 1., 1., 1.])})
    172         color_mode = values['color_mode']
    173         if color_mode == ColorMode.CYCLE:
--> 174             colors, values = _validate_cycle_mode(values)
        colors = undefined
        values = {'current_color': array([1., 1., 1., 1.]), 'color_mode': 'cycle', 'color_properties': ColorProperties(name='State', values=array([], dtype='<U12'), current_value=array('Interphase', dtype='<U10')), 'continuous_colormap': Colormap(colors=array([[0.26700401, 0.004874  , 0.32941499, 1.        ],
       [0.26851001, 0.009605  , 0.33542699, 1.        ],
       [0.26994401, 0.014625  , 0.34137899, 1.        ],
       ...,
       [0.97441697, 0.90359002, 0.130215  , 1.        ],
       [0.983868  , 0.90486699, 0.136897  , 1.        ],
       [0.99324799, 0.90615702, 0.14393599, 1.        ]]), name='viridis', interpolation='linear', controls=array([0.        , 0.00392157, 0.00784314, 0.01176471, 0.01568628,
       0.01960784, 0.02352941, 0.02745098, 0.03137255, 0.03529412,
       0.03921569, 0.04313726, 0.04705882, 0.05098039, 0.05490196,
       0.05882353, 0.0627451 , 0.06666667, 0.07058824, 0.07450981,
       0.07843138, 0.08235294, 0.08627451, 0.09019608, 0.09411765,
       0.09803922, 0.10196079, 0.10588235, 0.10980392, 0.11372549,
       0.11764706, 0.12156863, 0.1254902 , 0.12941177, 0.13333334,
       0.13725491, 0.14117648, 0.14509805, 0.14901961, 0.15294118,
       0.15686275, 0.16078432, 0.16470589, 0.16862746, 0.17254902,
       0.17647059, 0.18039216, 0.18431373, 0.1882353 , 0.19215687,
       0.19607843, 0.2       , 0.20392157, 0.20784314, 0.21176471,
       0.21568628, 0.21960784, 0.22352941, 0.22745098, 0.23137255,
       0.23529412, 0.23921569, 0.24313726, 0.24705882, 0.25098041,
       0.25490198, 0.25882354, 0.26274511, 0.26666668, 0.27058825,
       0.27450982, 0.27843139, 0.28235295, 0.28627452, 0.29019609,
       0.29411766, 0.29803923, 0.3019608 , 0.30588236, 0.30980393,
       0.3137255 , 0.31764707, 0.32156864, 0.32549021, 0.32941177,
       0.33333334, 0.33725491, 0.34117648, 0.34509805, 0.34901962,
       0.35294119, 0.35686275, 0.36078432, 0.36470589, 0.36862746,
       0.37254903, 0.3764706 , 0.38039216, 0.38431373, 0.3882353 ,
       0.39215687, 0.39607844, 0.40000001, 0.40392157, 0.40784314,
       0.41176471, 0.41568628, 0.41960785, 0.42352942, 0.42745098,
       0.43137255, 0.43529412, 0.43921569, 0.44313726, 0.44705883,
       0.4509804 , 0.45490196, 0.45882353, 0.4627451 , 0.46666667,
       0.47058824, 0.47450981, 0.47843137, 0.48235294, 0.48627451,
       0.49019608, 0.49411765, 0.49803922, 0.50196081, 0.50588238,
       0.50980395, 0.51372552, 0.51764709, 0.52156866, 0.52549022,
       0.52941179, 0.53333336, 0.53725493, 0.5411765 , 0.54509807,
       0.54901963, 0.5529412 , 0.55686277, 0.56078434, 0.56470591,
       0.56862748, 0.57254905, 0.57647061, 0.58039218, 0.58431375,
       0.58823532, 0.59215689, 0.59607846, 0.60000002, 0.60392159,
       0.60784316, 0.61176473, 0.6156863 , 0.61960787, 0.62352943,
       0.627451  , 0.63137257, 0.63529414, 0.63921571, 0.64313728,
       0.64705884, 0.65098041, 0.65490198, 0.65882355, 0.66274512,
       0.66666669, 0.67058825, 0.67450982, 0.67843139, 0.68235296,
       0.68627453, 0.6901961 , 0.69411767, 0.69803923, 0.7019608 ,
       0.70588237, 0.70980394, 0.71372551, 0.71764708, 0.72156864,
       0.72549021, 0.72941178, 0.73333335, 0.73725492, 0.74117649,
       0.74509805, 0.74901962, 0.75294119, 0.75686276, 0.76078433,
       0.7647059 , 0.76862746, 0.77254903, 0.7764706 , 0.78039217,
       0.78431374, 0.78823531, 0.79215688, 0.79607844, 0.80000001,
       0.80392158, 0.80784315, 0.81176472, 0.81568629, 0.81960785,
       0.82352942, 0.82745099, 0.83137256, 0.83529413, 0.8392157 ,
       0.84313726, 0.84705883, 0.8509804 , 0.85490197, 0.85882354,
       0.86274511, 0.86666667, 0.87058824, 0.87450981, 0.87843138,
       0.88235295, 0.88627452, 0.89019608, 0.89411765, 0.89803922,
       0.90196079, 0.90588236, 0.90980393, 0.9137255 , 0.91764706,
       0.92156863, 0.9254902 , 0.92941177, 0.93333334, 0.93725491,
       0.94117647, 0.94509804, 0.94901961, 0.95294118, 0.95686275,
       0.96078432, 0.96470588, 0.96862745, 0.97254902, 0.97647059,
       0.98039216, 0.98431373, 0.98823529, 0.99215686, 0.99607843,
       1.        ])), 'contrast_limits': None, 'categorical_colormap': CategoricalColormap(colormap={}, fallback_color=ColorCycle(values=array([[1., 1., 1., 1.]], dtype=float32), cycle=<itertools.cycle object at 0x7f99797a7be0>)), 'colors': array([], shape=(0, 4), dtype=float64)}
        global _validate_cycle_mode = <function _validate_cycle_mode at 0x7f9980d8fd40>
    175         elif color_mode == ColorMode.COLORMAP:
    176             colors, values = _validate_colormap_mode(values)

~/opt/anaconda3/envs/cnn-annotator/lib/python3.7/site-packages/napari/layers/utils/color_manager_utils.py in _validate_cycle_mode(values={'categorical_colormap': CategoricalColormap(colormap={}, fallback_color=...ycle=<itertools.cycle object at 0x7f99797a7be0>)), 'color_mode': 'cycle', 'color_properties': ColorProperties(name='State', values=array([], d... current_value=array('Interphase', dtype='<U10')), 'colors': array([], shape=(0, 4), dtype=float64), 'continuous_colormap': Colormap(colors=array([[0.26700401, 0.004874  , ...529, 0.99215686, 0.99607843,
       1.        ])), 'contrast_limits': None, 'current_color': array([1., 1., 1., 1.])})
    143         current_prop_value = values['color_properties'].current_value
    144         if current_prop_value is not None:
--> 145             values['current_color'] = cmap.map(current_prop_value)[0]
        values = {'current_color': array([1., 1., 1., 1.]), 'color_mode': 'cycle', 'color_properties': ColorProperties(name='State', values=array([], dtype='<U12'), current_value=array('Interphase', dtype='<U10')), 'continuous_colormap': Colormap(colors=array([[0.26700401, 0.004874  , 0.32941499, 1.        ],
       [0.26851001, 0.009605  , 0.33542699, 1.        ],
       [0.26994401, 0.014625  , 0.34137899, 1.        ],
       ...,
       [0.97441697, 0.90359002, 0.130215  , 1.        ],
       [0.983868  , 0.90486699, 0.136897  , 1.        ],
       [0.99324799, 0.90615702, 0.14393599, 1.        ]]), name='viridis', interpolation='linear', controls=array([0.        , 0.00392157, 0.00784314, 0.01176471, 0.01568628,
       0.01960784, 0.02352941, 0.02745098, 0.03137255, 0.03529412,
       0.03921569, 0.04313726, 0.04705882, 0.05098039, 0.05490196,
       0.05882353, 0.0627451 , 0.06666667, 0.07058824, 0.07450981,
       0.07843138, 0.08235294, 0.08627451, 0.09019608, 0.09411765,
       0.09803922, 0.10196079, 0.10588235, 0.10980392, 0.11372549,
       0.11764706, 0.12156863, 0.1254902 , 0.12941177, 0.13333334,
       0.13725491, 0.14117648, 0.14509805, 0.14901961, 0.15294118,
       0.15686275, 0.16078432, 0.16470589, 0.16862746, 0.17254902,
       0.17647059, 0.18039216, 0.18431373, 0.1882353 , 0.19215687,
       0.19607843, 0.2       , 0.20392157, 0.20784314, 0.21176471,
       0.21568628, 0.21960784, 0.22352941, 0.22745098, 0.23137255,
       0.23529412, 0.23921569, 0.24313726, 0.24705882, 0.25098041,
       0.25490198, 0.25882354, 0.26274511, 0.26666668, 0.27058825,
       0.27450982, 0.27843139, 0.28235295, 0.28627452, 0.29019609,
       0.29411766, 0.29803923, 0.3019608 , 0.30588236, 0.30980393,
       0.3137255 , 0.31764707, 0.32156864, 0.32549021, 0.32941177,
       0.33333334, 0.33725491, 0.34117648, 0.34509805, 0.34901962,
       0.35294119, 0.35686275, 0.36078432, 0.36470589, 0.36862746,
       0.37254903, 0.3764706 , 0.38039216, 0.38431373, 0.3882353 ,
       0.39215687, 0.39607844, 0.40000001, 0.40392157, 0.40784314,
       0.41176471, 0.41568628, 0.41960785, 0.42352942, 0.42745098,
       0.43137255, 0.43529412, 0.43921569, 0.44313726, 0.44705883,
       0.4509804 , 0.45490196, 0.45882353, 0.4627451 , 0.46666667,
       0.47058824, 0.47450981, 0.47843137, 0.48235294, 0.48627451,
       0.49019608, 0.49411765, 0.49803922, 0.50196081, 0.50588238,
       0.50980395, 0.51372552, 0.51764709, 0.52156866, 0.52549022,
       0.52941179, 0.53333336, 0.53725493, 0.5411765 , 0.54509807,
       0.54901963, 0.5529412 , 0.55686277, 0.56078434, 0.56470591,
       0.56862748, 0.57254905, 0.57647061, 0.58039218, 0.58431375,
       0.58823532, 0.59215689, 0.59607846, 0.60000002, 0.60392159,
       0.60784316, 0.61176473, 0.6156863 , 0.61960787, 0.62352943,
       0.627451  , 0.63137257, 0.63529414, 0.63921571, 0.64313728,
       0.64705884, 0.65098041, 0.65490198, 0.65882355, 0.66274512,
       0.66666669, 0.67058825, 0.67450982, 0.67843139, 0.68235296,
       0.68627453, 0.6901961 , 0.69411767, 0.69803923, 0.7019608 ,
       0.70588237, 0.70980394, 0.71372551, 0.71764708, 0.72156864,
       0.72549021, 0.72941178, 0.73333335, 0.73725492, 0.74117649,
       0.74509805, 0.74901962, 0.75294119, 0.75686276, 0.76078433,
       0.7647059 , 0.76862746, 0.77254903, 0.7764706 , 0.78039217,
       0.78431374, 0.78823531, 0.79215688, 0.79607844, 0.80000001,
       0.80392158, 0.80784315, 0.81176472, 0.81568629, 0.81960785,
       0.82352942, 0.82745099, 0.83137256, 0.83529413, 0.8392157 ,
       0.84313726, 0.84705883, 0.8509804 , 0.85490197, 0.85882354,
       0.86274511, 0.86666667, 0.87058824, 0.87450981, 0.87843138,
       0.88235295, 0.88627452, 0.89019608, 0.89411765, 0.89803922,
       0.90196079, 0.90588236, 0.90980393, 0.9137255 , 0.91764706,
       0.92156863, 0.9254902 , 0.92941177, 0.93333334, 0.93725491,
       0.94117647, 0.94509804, 0.94901961, 0.95294118, 0.95686275,
       0.96078432, 0.96470588, 0.96862745, 0.97254902, 0.97647059,
       0.98039216, 0.98431373, 0.98823529, 0.99215686, 0.99607843,
       1.        ])), 'contrast_limits': None, 'categorical_colormap': CategoricalColormap(colormap={}, fallback_color=ColorCycle(values=array([[1., 1., 1., 1.]], dtype=float32), cycle=<itertools.cycle object at 0x7f99797a7be0>)), 'colors': array([], shape=(0, 4), dtype=float64)}
        cmap.map = <bound method CategoricalColormap.map of CategoricalColormap(colormap={}, fallback_color=ColorCycle(values=array([[1., 1., 1., 1.]], dtype=float32), cycle=<itertools.cycle object at 0x7f99797a7be0>))>
        current_prop_value = array('Interphase', dtype='<U10')
    146     else:
    147         colors = cmap.map(color_properties)

~/opt/anaconda3/envs/cnn-annotator/lib/python3.7/site-packages/napari/utils/colormaps/categorical_colormap.py in map(self=CategoricalColormap(colormap={}, fallback_color=...ycle=<itertools.cycle object at 0x7f99797a7be0>)), color_properties=array('Interphase', dtype='<U10'))
     53         props_in_map = np.in1d(color_properties, color_cycle_keys)
     54         if not np.all(props_in_map):
---> 55             new_prop_values = color_properties[np.logical_not(props_in_map)]
        global new_prop_values = undefined
        color_properties = array('Interphase', dtype='<U10')
        global np.logical_not = <ufunc 'logical_not'>
        props_in_map = array([False])
     56             indices_to_add = np.unique(new_prop_values, return_index=True)[1]
     57             props_to_add = [

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

**Comment by jni** [comment]
Eeek! I can't quickly tell whether this break was an expected API change or a newly introduced bug. Thoughts @quantumjot @KristinaUlicna? Don't hesitate to reach out when we break stuff! :pray:

**Comment by quantumjot** [comment]
Hey @jni - 

So I managed to fix this by removing the `face_color_mode` property setter below:

```python
points_layer.face_color_cycle = COLOR_CYCLE
points_layer.face_color_mode = 'cycle'    # this line seems to cause the trouble
```
Not sure why this breaks things though :shrug:

**Comment by jni** [comment]
Looking around, `face_color_mode` is still part of the API. In my case, I don't get an error, but I did get [other errors](https://github.com/napari/napari/issues/2755) while trying to reproduce this one. So, I think there's plenty of bugs lurking in this part of the code base. We've been wanting to unify properties and colour handling across the whole code base, so hopefully we'll get this sorted at some point. Glad you have a workaround in the meantime!

**Comment by andy-sweet** [comment]
This or something very similar to it came up [on zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/points.20layer.20properties/near/245842509).

Hopefully the workaround mentioned here is OK for now. If it doesn't, another possible workaround is to pass `face_color` and `face_color_cycle` when creating the `Points` layer or when calling `Viewer.add_points`.

I created [issue #3039](https://github.com/napari/napari/issues/3039) in the napari repo to make sure this gets fixed either soon, or as part of properties/color unification work that @jni mentioned above.
