### ISSUE TITLE
`get_image_patch` function doesn't account for edge cells

### ISSUE THREAD

**Issue by laureho** [lowe-lab-ucl/cnn-annotator#9]
Currently, when the function encounters an edge case, it results in an incorrect patch shape of `(0,)` that raises the `ValueError` & interrupts the export of annotations.zip. This means the zip file excludes all annotations from the edge case onwards.

https://github.com/lowe-lab-ucl/cnn-annotator/blob/9b4b9d3f9735eb7d8a45b2171a3f882e44a24912/notebooks/A_CNN_Annotation_with_Napari.ipynb#L204-L218

Need to add to the function padding and/or flagging for edge cells.

**Comment by quantumjot** [comment]
BTW - we have a related issue in `cellx` - we should try to re-use the code if possible. See https://github.com/quantumjot/cellx/issues/24
